# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR .

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000
ENV FLASK_APP=trading.py
CMD ["gunicorn", "--threads", "4", "--bind", "0.0.0.0:5000", "trading:app"]
